name: trips_plus
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  font_awesome_flutter: 10.1.0
  json_annotation: 4.5.0
  # cloud_firestore: ^4.8.2 

  # google_sign_in: ^6.1.4
  

  # sign_in_with_apple: ^5.0.0
  # crypto: ^3.0.3
  
  # old firebase stuff
  # firebase_core: 1.18.0
  # cloud_firestore: 3.1.18
  # firebase_auth: 3.3.20
  # google_sign_in: 5.3.3
  # sign_in_with_apple: 4.0.0
  # crypto: 3.0.1
  
  # google_fonts: 3.0.1
  # provider: 6.0.3
  # rxdart: 0.27.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: 2.1.11
  json_serializable: 6.2.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - assets/covers/
  #   - assets/congrats.gif